.TH DRAWEXE 1 "OpenCASCADE test harness" "DEBIAN" \" -*- nroff -*-
.SH NAME
DRAWEXE \- OpenCASCADE test harness
.SH SYNOPSIS
\fBDRAWEXE\fP
.SH DESCRIPTION
This program provides a kind of scripting interface to the OpenCASCADE
libraries.  You can perform a simple test by starting it and entering at the
command line: "pload ALL" then "source /usr/share/opencascade/6.5.0/src/DrawResources/VisualizationDemo.tcl".
.SH AUTHOR
Adam Powell <hazelsct@debian.org>
